### ISSUE TITLE
Why not use GMP num?

### ISSUE THREAD

**Issue by spartucus** [mimblewimble/secp256k1-zkp#50]
From [here](https://github.com/mimblewimble/secp256k1-zkp/blob/master/src/basic-config.h#L25-L29), the library use builtin num instead of GMP num.

```
#define USE_NUM_NONE 1
#define USE_FIELD_INV_BUILTIN 1
#define USE_SCALAR_INV_BUILTIN 1
#define USE_FIELD_10X26 1
#define USE_SCALAR_8X32 1
```

I tested it on local, GMP version is 3 times faster than builtin. What's the consideration?

**Comment by garyyu** [comment]
@spartucus  interesting, what test did you launch for getting that `3 times faster` result?

**Comment by spartucus** [comment]
I tested it use our algorithms based on this repo, the algorithms was contains the following functions：
 `secp256k1_ecmult`, `secp256k1_ecmult_gen`, `scalar`, `ge`, `sha256` related functions. 

Sorry the code is not open sourced, so I can't tell much about it.

It was not the perfect test model, but when I call it use GMP version, it takes 4ms, and for builtin version, it takes 13ms.

My laptop is MacOS 10.14.6 with 2.8 GHz Intel Core i7 and SSD.

**Comment by spartucus** [comment]
And here is a related reading: https://github.com/bitcoin-core/secp256k1/pull/290
